//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinikSefler.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_minikseflerEntities : DbContext
    {
        public db_minikseflerEntities()
            : base("name=db_minikseflerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> address { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<city> city { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<product_image> product_image { get; set; }
        public DbSet<user> user { get; set; }
    }
}
