//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinikSefler.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public Nullable<int> EntryDate { get; set; }
        public Nullable<int> EntryTime { get; set; }
        public string EntryBy { get; set; }
        public Nullable<int> UpdateDate { get; set; }
        public Nullable<int> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> WantNewsletter { get; set; }
        public string ActivationCode { get; set; }
    }
}
